## DEV ORACLE CONFIG
export DEV_ORACLE_USER="sabarish"
export DEV_ORACLE_PASSWORD="Nls123"
export DEV_ORACLE_HOST="127.0.0.1" # Password needs to be encrypted
export DEV_ORACLE_PORT=1521
export DEV_ORACLE_SID="orcl"

## CLOUD TESTING ENVIRONMENT MYSQL CONFIG
export CLOUDTESTING_ORACLE_USER="ug_ncba"
export CLOUDTESTING_ORACLE_PASSWORD="Nls123" # Password needs to be encrypted
export CLOUDTESTING_ORACLE_HOST="127.0.0.1" 
export CLOUDTESTING_ORACLE_PORT=1521
export CLOUDTESTING_ORACLE_SID="orcl"

export DEV_ML_USERNAME="ML_USER"

## FLASK API CONFIG
export FLASK_API_NAME="flask_api"
export FLASK_API_VERSION="V0.01"
export FLASK_API_DOCKERFILE_NAME="Dockerfile-Flask"
export FLASK_API_CONTAINER_NAME="FLASK_API_DEV"
