## DEV MYSQL CONFIG
export DEV_MYSQL_USER="root"
export DEV_MYSQL_PASSWORD="Nls@123" # Password needs to be encrypted
export DEV_MYSQL_HOST="127.0.0.1"
export DEV_MYSQL_PORT=3306
export DEV_MYSQL_DB="aml_sidian"
export DEV_MYSQL_AUTH_PLUGIN="mysql_native_password"
export DEV_MYSQL_RAISE_WARNING=true

## CLOUD TESTING ENVIRONMENT MYSQL CONFIG
export CLOUDTESTING_MYSQL_USER="root"
export CLOUDTESTING_MYSQL_PASSWORD="root" # Password needs to be encrypted
export CLOUDTESTING_MYSQL_HOST="127.0.0.1" 
export CLOUDTESTING_MYSQL_PORT=3307
export CLOUDTESTING_MYSQL_DB="aml_sidian"
export CLOUDTESTING_MYSQL_AUTH_PLUGIN="mysql_native_password"
export CLOUDTESTING_MYSQL_RAISE_WARNING=true


export DEV_ML_USERNAME="ML_USER"

## FLASK API CONFIG
export FLASK_API_NAME="flask_api"
export FLASK_API_VERSION="V0.01"
export FLASK_API_DOCKERFILE_NAME="Dockerfile-Flask"
export FLASK_API_CONTAINER_NAME="FLASK_API_DEV"
