CREATE TABLE  `transaction$charge$codes` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRANSACTION_TYPE` varchar(255) NOT NULL,
  `TRANSACTION_NAME` varchar(255) NOT NULL,
  `TRANSACTION_CODE` varchar(45) NOT NULL,
  `CHARGE_TRANSACTION_CODE` varchar(45) NOT NULL,
  `TAX_TRANSACTION_CODE` varchar(45) DEFAULT NULL,
  `CHARGE_CODE` varchar(255) DEFAULT NULL,
  `TAX` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into `transaction$charge$codes` 
(`TRANSACTION_TYPE`,`TRANSACTION_NAME`,`TRANSACTION_CODE`,`CHARGE_TRANSACTION_CODE`,`TAX_TRANSACTION_CODE`,`CHARGE_CODE`,`TAX`)
values('MOBILE','MOBILE-EFT-91','186','245','465','EFTSTF','20%');
insert into `transaction$charge$codes`
(`TRANSACTION_TYPE`,`TRANSACTION_NAME`,`TRANSACTION_CODE`,`CHARGE_TRANSACTION_CODE`,`TAX_TRANSACTION_CODE`,`CHARGE_CODE`,`TAX`)
values('MOBILE','MOBILE-RTGS-92',781,230,465,'RTGSCHG','20%');
insert into `transaction$charge$codes` 
(`TRANSACTION_TYPE`,`TRANSACTION_NAME`,`TRANSACTION_CODE`,`CHARGE_TRANSACTION_CODE`,`TAX_TRANSACTION_CODE`,`CHARGE_CODE`,`TAX`)
values('MOBILE','MOBILE-STATEMENT-62',522,464,465,'VBSTATEMENT','20%');

insert into `transaction$charge$codes` 
(`TRANSACTION_TYPE`,`TRANSACTION_NAME`,`TRANSACTION_CODE`,`CHARGE_TRANSACTION_CODE`,`TAX_TRANSACTION_CODE`,`CHARGE_CODE`,`TAX`)
values('ATM','ATM-WITHDRAWAL-01',466,466,465,'ATMCHG','20%');

insert into `transaction$charge$codes` 
(`TRANSACTION_TYPE`,`TRANSACTION_NAME`,`TRANSACTION_CODE`,`CHARGE_TRANSACTION_CODE`,`TAX_TRANSACTION_CODE`,`CHARGE_CODE`,`TAX`)
values('IB','IB-KRA-12',935,234,465,'KRACHARGE','20%');
insert into `transaction$charge$codes` 
(`TRANSACTION_TYPE`,`TRANSACTION_NAME`,`TRANSACTION_CODE`,`CHARGE_TRANSACTION_CODE`,`TAX_TRANSACTION_CODE`,`CHARGE_CODE`,`TAX`)
values('IB','IB_PESALINK-70',738,234,465,'KITSCOMM',null);
insert into `transaction$charge$codes` 
(`TRANSACTION_TYPE`,`TRANSACTION_NAME`,`TRANSACTION_CODE`,`CHARGE_TRANSACTION_CODE`,`TAX_TRANSACTION_CODE`,`CHARGE_CODE`,`TAX`)
values('IB','IB_PESALINK-70',738,51,null,'PESALINKCHG',null);

ALTER TABLE `transaction$charge$codes` ADD `IS_ALWAYS_REGENERATE` bool null;
ALTER TABLE `transaction$charge$codes` MODIFY `IS_ALWAYS_REGENERATE` bool NOT NULL;