CREATE TABLE  `classification$model$information` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MODEL_NAME` varchar(200) NOT NULL,
  `FILE_NAME` varchar(200) NOT NULL,
  `SCALAR_NAME` varchar(200) NOT NULL,
  `ACCURACY` float NOT NULL,
  `F1_SCORE` float DEFAULT NULL,
  `SENSITIVITY` float DEFAULT NULL,
  `SPECIFICITY` float DEFAULT NULL,
  `FALSE_POSITIVE` float DEFAULT NULL,
  `FALSE_NEGATIVE` float DEFAULT NULL,
  `DATASET_COLUMNS` varchar(5000) NOT NULL,
  `ONEHOT_LIST` varchar(5000) NOT NULL,
  `CREATED_BY` varchar(200) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL,
  `UPDATED_BY` varchar(200) DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;